- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

# - name: Install Docker Module for Python
#   ansible.builtin.pip:
#     name: docker

- name: Create "docker" group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add remote user to "docker" group
  ansible.builtin.user:
    name: "{{ run_as_user }}"
    groups: docker
    append: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure Docker daemons starts on boot
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - docker.service
    - containerd.service
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: +x
