version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  caddy:
    image: caddy:alpine
    container_name: caddy_server
    restart: unless-stopped
    env_file:
      - caddy.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
        # caddy
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
        # logging
      - /var/log/caddy/:/var/log/
        # snapdrop
      - $PWD/snapdrop/client/:/usr/share/caddy/html/snapdrop/

  pastefy_db:
    image: mariadb:latest
    profiles:
      - pastefy
    volumes:
      - pastefy_db_vol:/var/lib/mysql
    env_file:
      - caddy.env

  pastefy:
    depends_on:
      - pastefy_db
    image: interaapps/pastefy:latest
    profiles:
      - pastefy
    env_file:
      - caddy.env

  snapdrop:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./snapdrop/server/:/home/node/app
    command: ash -c "npm i && node index.js"


volumes:
  caddy_data:
    external: true
  caddy_config:
  pastefy_db_vol:
